### ISSUE TITLE
Importlib issue

### ISSUE THREAD

**Issue by ErwannMillon** [hugofloresgarcia/audiotools#1]
Hey :)
Tried to install this to run vampnet. 

Get this issue on import 

Traceback (most recent call last):
  File "/home/erwann/vampnet/scripts/exp/train.py", line 9, in <module>
    import audiotools as at
  File "/opt/conda/envs/vamp/lib/python3.9/site-packages/audiotools/__init__.py", line 2, in <module>
    from .core import AudioSignal
  File "/opt/conda/envs/vamp/lib/python3.9/site-packages/audiotools/core/__init__.py", line 2, in <module>
    from .audio_signal import AudioSignal
  File "/opt/conda/envs/vamp/lib/python3.9/site-packages/audiotools/core/audio_signal.py", line 24, in <module>
    from .playback import PlayMixin
  File "/opt/conda/envs/vamp/lib/python3.9/site-packages/audiotools/core/playback.py", line 19, in <module>
    headers = pkg_resources.read_text(templates, "headers.html")
AttributeError: module 'importlib_resources' has no attribute 'read_text'

Running python 3.9.16 in a conda env on Ubuntu 18.04, also tried installing from the previous audiotools commit, but have the same error. 

Thanks for the great work :)

**Comment by hugofloresgarcia** [comment]
Hi! This should be fixed in the most recent code: https://github.com/hugofloresgarcia/audiotools/blob/f93514d46671b06c11114d3804ffe2b4086837aa/audiotools/core/playback.py#L20

This fork is just here temporarily while I adapt the vampnet codebase to the latest [audiotools](https://github.com/descriptinc/audiotools) code. 

Thanks for the catch! Feel free to close if this resolves the issue for you.
