### ISSUE TITLE
No such file or directory headers.html

### ISSUE THREAD

**Issue by camenduru** [hugofloresgarcia/audiotools#2]
Hi @hugofloresgarcia thanks for the vampnet ❤ we have started receiving this error.

```py
Status Legend:
(OK):download completed.
/content/vampnet
Traceback (most recent call last):
  File "/content/vampnet/app.py", line 10, in <module>
    import audiotools as at
  File "/usr/local/lib/python3.10/dist-packages/audiotools/__init__.py", line 2, in <module>
    from .core import AudioSignal
  File "/usr/local/lib/python3.10/dist-packages/audiotools/core/__init__.py", line 2, in <module>
    from .audio_signal import AudioSignal
  File "/usr/local/lib/python3.10/dist-packages/audiotools/core/audio_signal.py", line 24, in <module>
    from .playback import PlayMixin
  File "/usr/local/lib/python3.10/dist-packages/audiotools/core/playback.py", line 19, in <module>
    headers = pkg_resources.files(templates).joinpath("headers.html").read_text()
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/audiotools/core/templates/headers.html'
```

**Comment by camenduru** [comment]
I found the problem 🥳 https://github.com/descriptinc/audiotools/compare/master...camenduru:audiotools:vampnet

**Comment by camenduru** [comment]
this is working 🥳 `git+https://github.com/descriptinc/audiotools@0.7.2`
